# frozen_string_literal: true

source "https://rubygems.org"

gem 'nokogiri',           '~> 1.11'
gem 'httparty',           '~> 0.17.0'
gem 'pry',  	          '~> 0.12.2'
gem 'selenium-webdriver', '~> 3.5'
gem 'capybara',           '~> 3.28'
